---
- name: Install postgresql server
  yum:
    name:
      - postgresql-server
    state: present
  notify: 
    - Initialize postgres db
    - Start and enable postgresql service.

- name: Install packages - epel-release
  yum:
    name:
      - epel-release
    state: present
