---
- name: Install postgresql server
  yum:
    name:
      - postgresql-server
    state: present
  notify: 
    - Initialize postgres db
    - Start and enable postgresql service.

- name: Install packages - epel-release
  yum:
    name:
      - epel-release
    state: present

- name: Install python-pip and python-psycopg2
  yum:
    name:
      - python-pip
      - python-psycopg2
    state: present

- name: Install psycopg2-binary pip package
  pip:
    name: psycopg2-binary

