---
- name: Install packages - epel-release
  yum:
    name:
      - epel-release
    state: present

- name: Install python-pip, python-devel, gcc, nginx, git, psycopg2
  yum:
    name:
      - python-pip
      - python-devel
      - gcc
      - nginx
      - git
      - python-psycopg2
    state: present

- name: Create the project group myprojectuser.
  group: 
    name: myprojectuser
    state: present

- name: Create the project user myprojectuser.
  user:
    name: myprojectuser
    uid: 1040
    group: myprojectuser

- name: Install virtualenv
  pip:
    name: virtualenv

- name: Create virtualenv
  shell: /usr/bin/virtualenv /home/myprojectuser/myprojectenv

- name: Install flask, gunicorn, sqlalchemy and psycopg2-binary in myprojectenv
  pip:
    name: 
      - flask
      - gunicorn
      - sqlalchemy
      - psycopg2-binary
    virtualenv: /home/myprojectuser/myprojectenv

- name: Create directory myproject.
  file:
    path: /home/myprojectuser/myproject
    state: directory
    owner: myprojectuser
    group: myprojectuser
    recurse: yes
    mode: 0770

- name: Clone the example flaskr webapp into the VM.
  git:
    repo: https://github.com/nayakshweta/infrastructure_as_code_example.git
    dest: /home/myprojectuser/myproject
    version: postgres

- name: Initialize the db for flask.
  command: /home/myprojectuser/myprojectenv/bin/python flask_init_db.py
  args:
    chdir: /home/myprojectuser/myproject/webapp

- name: Assign the owner and group myprojectuser rwx permissions on the user home directory.
  file:
    path: /home/myprojectuser
    owner: myprojectuser
    group: myprojectuser
    recurse: yes
    mode: 0770

- name: Copy the service template file for myproject into /etc/systemd/system.
  template:
    src: myproject.service
    dest: /etc/systemd/system
  notify: Start and enable the myproject service.

- name: Copy the nginx.conf template into the VM.
  template:
    src: nginx.conf
    dest: /etc/nginx

- name: Add the nginx user to myprojectuser group.
  user:
    name: nginx
    groups: myprojectuser
    append: yes
  notify: Start and enable the nginx service.