---
- name: Install packages - epel-release
  yum:
    name:
      - epel-release
    state: present

- name: Install python-pip, python-devel, gcc, nginx
  yum:
    name:
      - python-pip
      - python-devel
      - gcc
      - nginx
    state: present